added a solution for task 2.1
ArtVyatkin/HomeWork pull request #10
Opened 2019-10-14 19:15 UTC by ArtVyatkin

2019-10-31 15:10 UTC, SpirinEgor requested changes

2019-10-31 15:10 UTC, SpirinEgor commented on Tasks_2/Task_2_1.c
> +    char* partition = (char*) calloc(0 , sizeof(char));
пробел лишний затесался

2019-10-31 15:10 UTC, SpirinEgor commented on Tasks_2/Task_2_1.c
> +void shortenString(char string[], int newLengthOfString)
Лучше не использовать `string`, как название. Ассоциируется с типом данных.

2019-10-31 15:10 UTC, SpirinEgor commented on Tasks_2/Task_2_1.c
> +void printPartitionOfNumber(int number, int maximumTermInPartition, char* partOfPartition, int lengthOfPreviousAddingString)
Не очень понятно, для чего использовать строку для хранения ответа, так как приходится постоянно кастовать числа и прочие сопутствующие операции. Лучше хранить массив слагаемых и добавить функцию вывода его.

2019-11-23 10:43 UTC, fefaleksey approved these changes
В целом ок, зачет

2019-11-23 10:43 UTC, fefaleksey commented on Tasks_2/Task_2_1.c
> +        printf("%d\n", partition[currentNumberOfTerms - 1]);
Если делать так, то в выводе появляется лишний пробел)

2019-11-23 10:43 UTC, fefaleksey commented on Tasks_2/Task_2_1.c
> +        printf("%d\n", partition[currentNumberOfTerms - 1]);
В самом начале

2019-11-23 11:06 UTC, merged