added a solution for task 3.1
ArtVyatkin/HomeWork pull request #11
Opened 2019-10-18 20:41 UTC by ArtVyatkin

2019-11-20 10:06 UTC, SpirinEgor requested changes

2019-11-20 10:06 UTC, SpirinEgor commented on Tasks_3/Task_3_1.c
> +void siftDownElement(int heap[], int indexOfElement, int sizeOfHeap)
Наверное, `shift` должно быть

2019-11-20 10:06 UTC, SpirinEgor commented on Tasks_3/Task_3_1.c
> +    int indexOfLeftChild = indexOfRightChild - 1;
Мне кажется, что понятнее будет, если посчитать индекс левого, аналогично
`indexOfElement * 2 + 1`

2019-11-20 10:28 UTC, ArtVyatkin commented on Tasks_3/Task_3_1.c
> +void siftDownElement(int heap[], int indexOfElement, int sizeOfHeap)
Я хотел записать "просеять элемент"

2019-11-20 10:28 UTC, ArtVyatkin commented on Tasks_3/Task_3_1.c
> +void siftDownElement(int heap[], int indexOfElement, int sizeOfHeap)
Лучше просто siftElement?

2019-11-20 12:41 UTC, SpirinEgor commented on Tasks_3/Task_3_1.c
> +void siftDownElement(int heap[], int indexOfElement, int sizeOfHeap)
Аа, понял
Думал, что хочешь "опустить вниз элемент", Down запутало немного.
Ну да, пусть будет просто `siftElement`

2019-12-01 21:13 UTC, fefaleksey approved these changes
ok

2019-12-02 17:02 UTC, merged