added a solution to task 4.2
ArtVyatkin/HomeWork pull request #15
Opened 2019-10-29 19:53 UTC by ArtVyatkin

2019-11-21 09:42 UTC, SpirinEgor requested changes

2019-11-21 09:42 UTC, SpirinEgor commented on Tasks_4/Task_4_2/Task_4_2.c
> +    while (true)
Можно сделать цикл: пока `action` не `EXIT`, а кусок свитча для `EXIT` перенести после `while`

2019-11-21 09:42 UTC, SpirinEgor commented on Tasks_4/Task_4_2/phoneBook.c
> +
Наплодил пустых строк в конце

2019-11-21 09:59 UTC, ArtVyatkin commented on Tasks_4/Task_4_2/Task_4_2.c
> +    while (true)
Может проверку на EXIT вообще тогда убрать из свитча? Он всё равно тогда не выполнится. Или лучше оставить для большей понятности?

2019-12-08 20:25 UTC, fefaleksey requested changes

2019-12-08 20:25 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +    scanStringWithSpaces(stdin, phoneNumber, maxSizeOfPhoneNumber);
> "Enter user phone number (without spaces): "
> scanStringWithSpaces(...)
Что-то тут не так

2019-12-08 20:25 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +    }
Печатать что-либо на экран -- обязанность другой функции. Функция "find" должна только искать

2019-12-08 20:25 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +    scanStringWithSpaces(stdin, phoneNumber, maxSizeOfPhoneNumber);
Как-то не очень убедительно)

2019-12-08 20:25 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +    FILE* fileOutput = fopen(nameOfFile, "a+");
А если он не открылся?

2019-12-08 20:25 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +
Слишком много отступов)

2019-12-10 11:43 UTC, jzuken requested changes

2019-12-10 11:43 UTC, jzuken commented on Tasks_4/Task_4_2/Task_4_2.c
> +int main()
открыл, сразу закрыл, потерял 160 байт

2019-12-10 11:43 UTC, jzuken commented on Tasks_4/Task_4_2/Task_4_2.c
> +    EXIT = 0,
а чего они капсом?

2019-12-10 11:43 UTC, jzuken commented on Tasks_4/Task_4_2/Task_4_2.c
> +    return symbol - '0';
а если оно не цифра?

2019-12-10 11:43 UTC, jzuken commented on Tasks_4/Task_4_2/Task_4_2.c
> +    bool isFindName = getNameByPhone(phoneBook, name, phoneNumber);
foundName

2019-12-10 11:43 UTC, jzuken commented on Tasks_4/Task_4_2/phoneBook.c
> +    int strcmpReturn = 0;
а нельзя попроще имя придумать?

2019-12-19 20:47 UTC, fefaleksey requested changes
Кажется тут что-то не так

Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.
Please enter a valid value.

......................

2019-12-19 20:47 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +    else return -1;
1) else return 1 -- не слишком ли много в одной строчке (скобочки надо ставить, да)?
2) зачем тут вообще else?

2019-12-19 20:47 UTC, fefaleksey commented on Tasks_4/Task_4_2/Task_4_2.c
> +void getAction(int* action, char* nameOfFile)
Не проще ли вернуть action?

2019-12-22 11:41 UTC, fefaleksey approved these changes
ok

2019-12-23 20:55 UTC, merged