added a solution to task 5.2
ArtVyatkin/HomeWork pull request #16
Opened 2019-11-11 22:10 UTC by ArtVyatkin

2019-11-21 13:25 UTC, SpirinEgor requested changes

2019-11-21 13:25 UTC, SpirinEgor commented on Tasks_5/Task_5_2/Task_5_2.c
> +            return (double)firstNumber / (double)secondNumber;
оба числа уже double, зачем ещё раз кастовать?

2019-11-25 20:15 UTC, fefaleksey requested changes

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +    scanf("%[^\n]", stringBuffer);
Вам же сказали не пользоваться таким вводом больше и исправить его во всех домашках

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/stack.h
> +#define STACK_H
#pragma once

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/stack.c
> +#include <stdlib.h>
Проверки на NULL для слабаков видимо, ни одной по коду не увидел

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +    scanf("%[^\n]", stringBuffer);
И на NULL неплохо бы проверить параметры

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +{
Слишком длинная функция

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +{
Слишком длинная функция

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +}
Они и так откастятся

2019-11-25 20:15 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +    return (int)symbol - (int)'0';
Они и так откастятся

2019-11-25 20:20 UTC, fefaleksey requested changes

2019-11-25 20:20 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +    return (int)symbol - (int)'0';
Они и так откастятся

2019-11-25 20:20 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +    return (int)symbol - (int)'0';
Они и так откастятся

2019-11-25 20:20 UTC, fefaleksey requested changes

2019-11-25 20:20 UTC, fefaleksey commented on Tasks_5/Task_5_2/Task_5_2.c
> +    return (int)symbol - (int)'0';
Они и так откастятся

2019-11-25 20:35 UTC, ArtVyatkin commented on Tasks_5/Task_5_2/stack.h
> +#define STACK_H
Это необходимо? Просто нам говорили делать проверку через #ifndef

2019-12-10 13:31 UTC, SpirinEgor requested changes

2019-12-10 13:31 UTC, SpirinEgor commented on Tasks_5/Task_5_2/Task_5_2.c
> +    else return -1;
Либо стаивть фигурные скобки, либо убирать else

2019-12-10 13:31 UTC, SpirinEgor commented on Tasks_5/Task_5_2/Task_5_2.c
> +bool calculatePostfixExpression(char* postfixExpression, double* resultOfExpression)
Не перед всеми return делается очистка памяти

2019-12-22 11:52 UTC, fefaleksey approved these changes

2019-12-23 20:55 UTC, merged