added a solution to task 2.4
ArtVyatkin/HomeWork pull request #2
Opened 2019-09-30 21:49 UTC by ArtVyatkin

2019-10-07 13:37 UTC, SpirinEgor requested changes

2019-10-07 13:37 UTC, SpirinEgor commented on Tasks_2/Task_2_4.c
> +    int upIterator = leftElement, downIterator = rightElement;
Выражения лучше писать по одному в каждой строчке.

2019-10-07 13:37 UTC, SpirinEgor commented on Tasks_2/Task_2_4.c
> +//This method sorts descending
This method sorts in descending order

2019-10-07 13:37 UTC, SpirinEgor commented on Tasks_2/Task_2_4.c
> +int getIndexOfRepeatingMax(int array[], int sizeOfArray)
Функция возвращает индекс максимального элемента, чтобы потом обратиться по этому индексу и вывести сам элемент. Более того, если эта функция нужна для решения задачи, то в ней требуют именно элемент, а не индекс. Поэтому логичнее назвать функцию `getMaximumRepeatingElement` и возвращать сразу сам элемент.

2019-10-08 20:18 UTC, ArtVyatkin commented on Tasks_2/Task_2_4.c
> +int getIndexOfRepeatingMax(int array[], int sizeOfArray)
Возвращая индекс, я дополнительно мог осуществить проверку на наличие повторяющегося элемента, так как значения индексов неотрицательны

2019-10-22 11:28 UTC, merged