added a solution for task 2.3
ArtVyatkin/HomeWork pull request #9
Opened 2019-10-14 10:28 UTC by ArtVyatkin

2019-10-31 15:30 UTC, SpirinEgor requested changes

2019-10-31 15:30 UTC, SpirinEgor commented on Tasks_2/Task_2_3.c
> +    EXIT
А здесь значение поставить?

2019-10-31 15:30 UTC, SpirinEgor commented on Tasks_2/Task_2_3.c
> +bool isInSecretNumber(int checkingDigit, int secretNumber[])
Данная функция применяется не только в этом контексте, логичнее её назвать `isDigitInNumber`, ну и аргументы соответсвующие.

2019-10-31 15:30 UTC, SpirinEgor commented on Tasks_2/Task_2_3.c
> +enum GameAction
для `enum` вроде то же можно `typedef` задать

2019-10-31 15:32 UTC, ArtVyatkin commented on Tasks_2/Task_2_3.c
> +    EXIT
Они разве не автоматически задаются?

2019-11-23 11:01 UTC, fefaleksey commented on Tasks_2/Task_2_3.c
> +}
Тебя ничего тут не смущает? GameAction* и int* -- это немного разные вещи

2019-11-23 11:01 UTC, fefaleksey commented on Tasks_2/Task_2_3.c
> +    int secretNumber[lengthOfSecretNumber] = {0};
Это не соответствует стандарту. GCC, например, не скомпилит.

2019-11-23 11:01 UTC, fefaleksey commented on Tasks_2/Task_2_3.c
> +    }
Я бы вынес это в отдельную функцию

2019-11-23 11:06 UTC, fefaleksey commented on Tasks_2/Task_2_3.c
> +    }
P.S. это надо исправить, да

2019-11-23 11:08 UTC, fefaleksey commented on Tasks_2/Task_2_3.c
> +    int secretNumber[lengthOfSecretNumber] = {0};
По стандарту можно только так
    int guessAsArray[lengthOfSecretNumber];
    int secretNumber[lengthOfSecretNumber];
либо сделать lengthOfSecretNumber символической константой и тогда можешь инициализировать (начиная с 11 стандарта если я правильно помню)

2019-11-23 11:22 UTC, ArtVyatkin commented on Tasks_2/Task_2_3.c
> +}
Мне казалось, что каждому элементу в enum ставится целочисленное значение в соответствие, и поэтому можно вводить через %d

2019-12-08 15:37 UTC, jzuken commented on Tasks_2/Task_2_3.c
> +    EXIT,
значения перечислений лучше именовать так же, как и обычные переменные

2019-12-08 15:37 UTC, merged